name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Installer Docker Compose
      - name: Install Docker Compose
        run: |
          COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)
          sudo curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Se connecter au registre Docker de GitHub avec PAT
      - name: Log in to GitHub Docker Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Construire et pousser l'image Docker du frontend
      - name: Build frontend Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/frontend:v1.2.0 -f ./frontend/Dockerfile ./frontend
          docker push ghcr.io/${{ github.repository }}/frontend:v1.2.0

      # Construire et pousser l'image Docker du backend
      - name: Build backend Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/backend:v1.2.0 -f ./backend/Dockerfile ./backend
          docker push ghcr.io/${{ github.repository }}/backend:v1.2.0

      # Déployer en utilisant Docker Compose
      - name: Deploy using Docker Compose
        run: docker-compose up -d
